name: myflutter
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  get: ^4.6.5
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  latlong2: ^0.9.0
  flutter_map: ^5.0.0
  url_launcher: ^6.1.12
  geolocator: ^9.0.2
  line_awesome_flutter: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.3.1
  intl: ^0.18.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  android_id: ^0.3.4
  device_info_plus: ^9.0.3
  flutter_local_notifications: ^15.1.1
  localization: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.1
  flutter_cache_manager: ^3.3.1
  built_value: ^8.6.2
  flutter_spinkit: ^5.2.0


flutter_launcher_icons:
  image_path: "assets/images/splash_screen_images/top_splash_screen.png"
  android: true
  ios: true
  adaptive_icon_background: "#f7f6f1"
  adaptive_icon_foreground: "assets/images/splash_screen_images/top_splash_screen.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_screen_images/top_splash_screen.png
  image_dark: assets/images/splash_screen_images/top_splash_screen.png

  android_12:
    image: assets/images/splash_screen_images/top_splash_screen.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/splash_screen_images/top_splash_screen.png
    icon_background_color_dark: "#272727"


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/splash_screen_images/
  - assets/images/on_boarding_images/
  - assets/images/welcome_images/
  - assets/images/profile_images/
  - assets/logo/
  - assets/images/traffic/

 