// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPDTbO5hYu1PS8v08TV3HhToyrk1YYzM',
    appId: '1:1003286560948:web:e2a283992b908429d6d7e1',
    messagingSenderId: '1003286560948',
    projectId: 'cleanchtracking',
    authDomain: 'cleanchtracking.firebaseapp.com',
    storageBucket: 'cleanchtracking.appspot.com',
    measurementId: 'G-D7C9EPZRXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3f1mY7BSzyO9LWnDfZI_E_Bz8V115Z8s',
    appId: '1:1003286560948:android:7a5aa0d50a35afc8d6d7e1',
    messagingSenderId: '1003286560948',
    projectId: 'cleanchtracking',
    storageBucket: 'cleanchtracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxX-pukioz5RD6CyxbWhkfqJuXTn7L9vY',
    appId: '1:1003286560948:ios:d51a5669feb8356bd6d7e1',
    messagingSenderId: '1003286560948',
    projectId: 'cleanchtracking',
    storageBucket: 'cleanchtracking.appspot.com',
    iosClientId: '1003286560948-u2j0o4v0pk0f3suckecidrdsfsuiffbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxX-pukioz5RD6CyxbWhkfqJuXTn7L9vY',
    appId: '1:1003286560948:ios:d51a5669feb8356bd6d7e1',
    messagingSenderId: '1003286560948',
    projectId: 'cleanchtracking',
    storageBucket: 'cleanchtracking.appspot.com',
    iosClientId: '1003286560948-u2j0o4v0pk0f3suckecidrdsfsuiffbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanch',
  );
}
